### ISSUE TITLE
Remoção do scroll na tabela do ```Dashboard```

### ISSUE THREAD

**Issue by humbertobarbosa** [humbertobarbosa/GLPI-react-components#3]
Remover barra de _scroll_ na tabela do ```Dashboard```
- Problema: com essa remoção, a tabela deixou de ser responsiva

**Comment by CharlieBellow** [comment]
em que sentido se dá essa responsividade? é importante detalhar o problema par que a gente possa entender e solucionar o problema.

**Comment by CharlieBellow** [comment]
falta resolver a responsividade do mobile
