### ISSUE TITLE
Validação de formulários

### ISSUE THREAD

**Issue by humbertobarbosa** [humbertobarbosa/GLPI-react-components#6]
Atribuir aos _inputs_ alguma característica que os tornem (in)válidos. No momento, existem duas opções de como realizar essa implementação:

1.  Utilização de bordas verdes e vermelhas para representar _inputs_ válidos e inválidos, respectivamente
2.  Utilização de borda cinza e fundo branco para marcar o _input_ como preenchido, de modo a diferenciá-lo dos outros _inputs_ que ainda estão vazios

**Comment by CharlieBellow** [comment]
ótimo! Vamos observar se no formik já tem algo que faça isso por padrão, se sim, usaremos essa validação padrão do formik caso ela não serja tão divergente do nosso layout.

**Comment by humbertobarbosa** [comment]
> ótimo! Vamos observar se no formik já tem algo que faça isso por padrão, se sim, usaremos essa validação padrão do formik caso ela não serja tão divergente do nosso layout.

Aparentemente o yup nos dá a opção de estilizarmos a validação da forma que acharmos melhor. A ferramenta por si só não faz isso por padrão.

**Comment by CharlieBellow** [comment]
a validação de formulário está funcionando, porém, não aceita ser importada de outro aquivo. Resolvi o problema importando apenas o objeto com as validações e passando as validações em cada página de formulário. Posteriormente, precisamos ver como conseguir importar a validação inteira para garantir um melhor aproveitamento de código.
